-- MySQL Script generated by MySQL Workbench
-- Sun Sep 29 02:29:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DiscountCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DiscountCard` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DiscountCard` (
  `id_discount` INT NOT NULL AUTO_INCREMENT,
  `discount_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_discount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerPurchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CustomerPurchases` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CustomerPurchases` (
  `id_purchases` INT NOT NULL AUTO_INCREMENT,
  `purchase_data` VARCHAR(45) NOT NULL,
  `purchase_price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_purchases`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Costumers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Costumers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Costumers` (
  `id_costumers` INT NOT NULL AUTO_INCREMENT,
  `costumer_name` VARCHAR(45) NOT NULL,
  `DiscountCard_id_discount` INT NOT NULL,
  `CustomerPurchases_id_purchases` INT NOT NULL,
  PRIMARY KEY (`id_costumers`),
  INDEX `fk_Costumers_DiscountCard_idx` (`DiscountCard_id_discount` ASC) VISIBLE,
  INDEX `fk_Costumers_CustomerPurchases1_idx` (`CustomerPurchases_id_purchases` ASC) VISIBLE,
  CONSTRAINT `fk_Costumers_DiscountCard`
    FOREIGN KEY (`DiscountCard_id_discount`)
    REFERENCES `mydb`.`DiscountCard` (`id_discount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costumers_CustomerPurchases1`
    FOREIGN KEY (`CustomerPurchases_id_purchases`)
    REFERENCES `mydb`.`CustomerPurchases` (`id_purchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Models` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Models` (
  `id_models` INT NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_models`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PhoneReviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PhoneReviews` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PhoneReviews` (
  `id_reviews` INT NOT NULL AUTO_INCREMENT,
  `review_text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reviews`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Phones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Phones` (
  `id_brands` INT NOT NULL AUTO_INCREMENT,
  `phone_brands_name` VARCHAR(45) NOT NULL,
  `Models_id_models` INT NOT NULL,
  `PhoneReviews_id_reviews` INT NOT NULL,
  PRIMARY KEY (`id_brands`),
  INDEX `fk_Brands_Models1_idx` (`Models_id_models` ASC) VISIBLE,
  INDEX `fk_Phones_PhoneReviews1_idx` (`PhoneReviews_id_reviews` ASC) VISIBLE,
  CONSTRAINT `fk_Brands_Models1`
    FOREIGN KEY (`Models_id_models`)
    REFERENCES `mydb`.`Models` (`id_models`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Phones_PhoneReviews1`
    FOREIGN KEY (`PhoneReviews_id_reviews`)
    REFERENCES `mydb`.`PhoneReviews` (`id_reviews`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Features` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Features` (
  `id_features` INT NOT NULL AUTO_INCREMENT,
  `features_name` VARCHAR(45) NOT NULL,
  `Models_id_models` INT NOT NULL,
  PRIMARY KEY (`id_features`),
  INDEX `fk_Features_Models1_idx` (`Models_id_models` ASC) VISIBLE,
  CONSTRAINT `fk_Features_Models1`
    FOREIGN KEY (`Models_id_models`)
    REFERENCES `mydb`.`Models` (`id_models`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PhoneStores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PhoneStores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PhoneStores` (
  `id_stores` INT NOT NULL AUTO_INCREMENT,
  `phone_store_name` VARCHAR(45) NOT NULL,
  `CustomerPurchases_id_purchases` INT NOT NULL,
  PRIMARY KEY (`id_stores`),
  INDEX `fk_PhoneStores_CustomerPurchases1_idx` (`CustomerPurchases_id_purchases` ASC) VISIBLE,
  CONSTRAINT `fk_PhoneStores_CustomerPurchases1`
    FOREIGN KEY (`CustomerPurchases_id_purchases`)
    REFERENCES `mydb`.`CustomerPurchases` (`id_purchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Primotions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Primotions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Primotions` (
  `id_promo` INT NOT NULL AUTO_INCREMENT,
  `promotion_name` VARCHAR(45) NOT NULL,
  `discount_amount` VARCHAR(45) NOT NULL,
  `Phones_id_brands` INT NOT NULL,
  PRIMARY KEY (`id_promo`, `Phones_id_brands`),
  INDEX `fk_Primotions_Phones1_idx` (`Phones_id_brands` ASC) VISIBLE,
  CONSTRAINT `fk_Primotions_Phones1`
    FOREIGN KEY (`Phones_id_brands`)
    REFERENCES `mydb`.`Phones` (`id_brands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PhoneStores_has_Phones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PhoneStores_has_Phones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PhoneStores_has_Phones` (
  `PhoneStores_id_stores` INT NOT NULL,
  `Phones_id_brands` INT NOT NULL,
  PRIMARY KEY (`PhoneStores_id_stores`, `Phones_id_brands`),
  INDEX `fk_PhoneStores_has_Phones_Phones1_idx` (`Phones_id_brands` ASC) VISIBLE,
  INDEX `fk_PhoneStores_has_Phones_PhoneStores1_idx` (`PhoneStores_id_stores` ASC) VISIBLE,
  CONSTRAINT `fk_PhoneStores_has_Phones_PhoneStores1`
    FOREIGN KEY (`PhoneStores_id_stores`)
    REFERENCES `mydb`.`PhoneStores` (`id_stores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PhoneStores_has_Phones_Phones1`
    FOREIGN KEY (`Phones_id_brands`)
    REFERENCES `mydb`.`Phones` (`id_brands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Primotions_has_PhoneStores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Primotions_has_PhoneStores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Primotions_has_PhoneStores` (
  `Primotions_id_promo` INT NOT NULL,
  `PhoneStores_id_stores` INT NOT NULL,
  PRIMARY KEY (`Primotions_id_promo`, `PhoneStores_id_stores`),
  INDEX `fk_Primotions_has_PhoneStores_PhoneStores1_idx` (`PhoneStores_id_stores` ASC) VISIBLE,
  INDEX `fk_Primotions_has_PhoneStores_Primotions1_idx` (`Primotions_id_promo` ASC) VISIBLE,
  CONSTRAINT `fk_Primotions_has_PhoneStores_Primotions1`
    FOREIGN KEY (`Primotions_id_promo`)
    REFERENCES `mydb`.`Primotions` (`id_promo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Primotions_has_PhoneStores_PhoneStores1`
    FOREIGN KEY (`PhoneStores_id_stores`)
    REFERENCES `mydb`.`PhoneStores` (`id_stores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phones_has_CustomerPurchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Phones_has_CustomerPurchases` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Phones_has_CustomerPurchases` (
  `Phones_id_brands` INT NOT NULL,
  `CustomerPurchases_id_purchases` INT NOT NULL,
  PRIMARY KEY (`Phones_id_brands`, `CustomerPurchases_id_purchases`),
  INDEX `fk_Phones_has_CustomerPurchases_CustomerPurchases1_idx` (`CustomerPurchases_id_purchases` ASC) VISIBLE,
  INDEX `fk_Phones_has_CustomerPurchases_Phones1_idx` (`Phones_id_brands` ASC) VISIBLE,
  CONSTRAINT `fk_Phones_has_CustomerPurchases_Phones1`
    FOREIGN KEY (`Phones_id_brands`)
    REFERENCES `mydb`.`Phones` (`id_brands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Phones_has_CustomerPurchases_CustomerPurchases1`
    FOREIGN KEY (`CustomerPurchases_id_purchases`)
    REFERENCES `mydb`.`CustomerPurchases` (`id_purchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
