-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 03:47:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema orderssql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orderssql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orderssql` DEFAULT CHARACTER SET utf8 ;
USE `orderssql` ;

-- -----------------------------------------------------
-- Table `orderssql`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderssql`.`Users` ;

CREATE TABLE IF NOT EXISTS `orderssql`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(45) NOT NULL,
  `user_age` INT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderssql`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderssql`.`Orders` ;

CREATE TABLE IF NOT EXISTS `orderssql`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_data` VARCHAR(45) NOT NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `Users_user_id`),
  INDEX `fk_Orders_Users1_idx` (`Users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `orderssql`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderssql`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderssql`.`Products` ;

CREATE TABLE IF NOT EXISTS `orderssql`.`Products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` INT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderssql`.`OrderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderssql`.`OrderDetails` ;

CREATE TABLE IF NOT EXISTS `orderssql`.`OrderDetails` (
  `OrderDetails_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `Product_product_id` INT NOT NULL,
  `Orders_order_id` INT NOT NULL,
  PRIMARY KEY (`OrderDetails_id`, `Product_product_id`, `Orders_order_id`),
  INDEX `fk_OrderDetails_Product1_idx` (`Product_product_id` ASC) VISIBLE,
  INDEX `fk_OrderDetails_Orders1_idx` (`Orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetails_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `orderssql`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetails_Orders1`
    FOREIGN KEY (`Orders_order_id`)
    REFERENCES `orderssql`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
